In [2]:
#Consider the below code to answer further questions:


import numpy as np

list_ = [ '1','2','3','4','5']

array_list = np.array(object = list_)


In [5]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables'''

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list'''

print("\nData type of each element of list_:")
for item in list_:
    print(type(item))

print("\nData type of each element of array_list:")
for item in array_list:
    print(type(item))


Data type of each element of list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element of array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
#Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

'''Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
'''
print("\nData type of each element of list_:")
for item in list_:
    print(type(item))

print("\nData type of each element of array_list:")
for item in array_list:
    print(type(item))


Data type of each element of list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element of array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [11]:
'''Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
a. shape
b. size'''

num_list =[[1,2,3],[4,5,6]]
num_array = np.array(object = num_list)
shape = num_array.shape
size = num_array.size
print(shape,size)

(2, 3) 6


In [12]:
#write a code to create numpy array of 3*3 matrix containing zeros only, using numpy array creation function

import numpy as np
zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# 6 Crate an identity matrix of shape (5,5) using numpy functions
id_matrix = np.identity(5)
print(id_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
